/*
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.

    Example 1 -
        Input - s = "abcd", t = "abcde"
        Output - "e"
        Explanation - 'e' is the letter that was added.

    Example 2 -
        Input - s = "", t = "y"
        Output - "y"
*/

public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] freqCountS = new int[26];
        for(char ch : s.toCharArray()){
            freqCountS[ch - 'a']++;
        }
        int[] freqCountT = new int[26];
        for(char ch : t.toCharArray()){
            freqCountT[ch - 'a']++;
        }
        for(int k = 0; k < freqCountT.length; k++){
            if(freqCountT[k] != freqCountS[k]){
                return (char)(k + 'a');
            }
        }
        // In order to satisfy the compiler... although we will never reach this line...
        return 'a';
    }
}